### ISSUE TITLE
Cant have multiple Latexsvg render in one callout

### ISSUE THREAD

**Issue by Ilithios06** [gboyd068/obsidian-swiftlatex-render#3]
When i tried having mutiple latexsvg pfds rendered in the same callout, it would only render one of the two. Both can render on their own outside of the callout and they can both be rendered simultaneously in the same callout. Check the images:
![image](https://github.com/gboyd068/obsidian-swiftlatex-render/assets/86689318/348e183c-075d-464c-8a44-647085ca881a)
![image](https://github.com/gboyd068/obsidian-swiftlatex-render/assets/86689318/a99a86d9-1398-4940-b028-7ed09ae5fb60)
![image](https://github.com/gboyd068/obsidian-swiftlatex-render/assets/86689318/0ec442b7-5aec-4034-9f52-c260cec47e0c)
I know that i could simply use the TikzJaz plugin for tihs, because im not using anything else than tikz with pgfplots, but i think this issue should still be looked into

**Comment by gboyd068** [comment]
Thanks for this! I never tested callouts with multiple diagrams and have immediately found what I think is a separate bug related to this (:
Could you provide a minimal example for this issue, as the quick examples I threw together couldn't reproduce the behaviour you're showing here.

**Comment by Ilithios06** [comment]
a minimal example would be something like this in its own note:

>[!note]
>```latexsvg
>\documentclass{standalone}
>\begin{document}
>test1
>\end{document}
>```
>```latexsvg
>\documentclass{standalone}
>\begin{document}
>test2
>\end{document}
>```

This seems to render either "test1" or "test2". The distribution of renders seem to be completely random. I managed to have both be rendered at the same time once, but i cant seem to reproduce it. Even when you have one of them be latexsvg and the other latex, it still only renders one of the 2.

**Comment by gboyd068** [comment]
Okay sorry I was thinking about embeds. The reason for this is that the plugin only uses one worker to compile latex and when using a callout both codeblocks try to use the worker at the same time.
This shouldn't be hard to fix so I'll work on it when I get some time, but a hacky solution in the meantime to get both of them rendered if you're desperate to use callouts is to render the diagram(s) elsewhere so that they are cached, and the worker doesn't need to be used.

**Comment by gboyd068** [comment]
Turns out I had some time today, if you reinstall the plugin it should be fixed
